name: SavorCue
options:
  bundleIdPrefix: com.savorcue
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "16.0"
  
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  
settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "6.0"

targets:
  SavorCue:
    type: application
    platform: iOS
    sources:
      - SavorCue
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.savorcue.app
      INFOPLIST_VALUES:
        CFBundleDisplayName: SavorCue
        UIBackgroundModes: [remote-notification, fetch]
        UILaunchStoryboardName: ""
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseMessaging

  WatchApp:
    type: application
    platform: watchOS
    sources:
      - WatchApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.savorcue.app.watchkitapp
      INFOPLIST_VALUES:
        CFBundleDisplayName: SavorCue
        WKCompanionAppBundleIdentifier: com.savorcue.app
        WKApplication: true
